apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root
spec:
  generators:
  - git:
      repoURL: https://github.com/clastix/argocd-example-apps.git
      revision: main
      directories:
      - path: ./*
      - path: ./root
        exclude: true
  template:
    metadata:
      name: '{{path[0]}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/clastix/argocd-example-apps.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
